import {burnDark} from './burn'
import {fizzDark} from './fizz'
import {heliosDark} from './helios'
import {limeDark} from './lime'
import {mauveDark} from './mauve'
import {moonDark} from './moon'
import {skyDark} from './sky'
import {slateDark} from './slate'

const baseKitDarkThemeColors = {
  white: '#000000',
  black: '#FFFFFF',
  primaryGray: '#232A2F',
  secondaryGray: '#161D1D',

  primaryBorder: `rgba(66, 76, 85, 0.5)`,
  primaryBorderHover: `rgba(66, 76, 85, 0.8)`,
  secondaryBorder: `rgba(40, 40, 40, 0.2)`,

  flag: 'rgba(74, 74, 74, 0.2)',
  blur: 'rgba(240,240,240,0.4)',

  atelier00: '#CEFE71',
  atelier01: '#BEBCA6',
  atelier02: '#A493F8',
  atelier03: '#837E95',

  slate1: slateDark.slate1,
  slate2: slateDark.slate2,
  slate3: slateDark.slate3,
  slate4: slateDark.slate4,
  slate5: slateDark.slate5,
  slate6: slateDark.slate6,
  slate7: slateDark.slate7,
  slate8: slateDark.slate8,
  slate9: slateDark.slate9,
  slate10: slateDark.slate10,
  slate11: slateDark.slate11,
  slate12: slateDark.slate12,

  mauve1: mauveDark.mauve1,
  mauve2: mauveDark.mauve2,
  mauve3: mauveDark.mauve3,
  mauve4: mauveDark.mauve4,
  mauve5: mauveDark.mauve5,
  mauve6: mauveDark.mauve6,
  mauve7: mauveDark.mauve7,
  mauve8: mauveDark.mauve8,
  mauve9: mauveDark.mauve9,
  mauve10: mauveDark.mauve10,
  mauve11: mauveDark.mauve11,
  mauve12: mauveDark.mauve12,

  helios1: heliosDark.helios1,
  helios2: heliosDark.helios2,
  helios3: heliosDark.helios3,
  helios4: heliosDark.helios4,
  helios5: heliosDark.helios5,
  helios6: heliosDark.helios6,
  helios7: heliosDark.helios7,
  helios8: heliosDark.helios8,
  helios9: heliosDark.helios9,
  helios10: heliosDark.helios10,
  helios11: heliosDark.helios11,
  helios12: heliosDark.helios12,

  fizz1: fizzDark.fizz1,
  fizz2: fizzDark.fizz2,
  fizz3: fizzDark.fizz3,
  fizz4: fizzDark.fizz4,
  fizz5: fizzDark.fizz5,
  fizz6: fizzDark.fizz6,
  fizz7: fizzDark.fizz7,
  fizz8: fizzDark.fizz8,
  fizz9: fizzDark.fizz9,
  fizz10: fizzDark.fizz10,
  fizz11: fizzDark.fizz11,
  fizz12: fizzDark.fizz12,

  lime1: limeDark.lime1,
  lime2: limeDark.lime2,
  lime3: limeDark.lime3,
  lime4: limeDark.lime4,
  lime5: limeDark.lime5,
  lime6: limeDark.lime6,
  lime7: limeDark.lime7,
  lime8: limeDark.lime8,
  lime9: limeDark.lime9,
  lime10: limeDark.lime10,
  lime11: limeDark.lime11,
  lime12: limeDark.lime12,

  sky1: skyDark.sky1,
  sky2: skyDark.sky2,
  sky3: skyDark.sky3,
  sky4: skyDark.sky4,
  sky5: skyDark.sky5,
  sky6: skyDark.sky6,
  sky7: skyDark.sky7,
  sky8: skyDark.sky8,
  sky9: skyDark.sky9,
  sky10: skyDark.sky10,
  sky11: skyDark.sky11,
  sky12: skyDark.sky12,

  burn1: burnDark.burn1,
  burn2: burnDark.burn2,
  burn3: burnDark.burn3,
  burn4: burnDark.burn4,
  burn5: burnDark.burn5,
  burn6: burnDark.burn6,
  burn7: burnDark.burn7,
  burn8: burnDark.burn8,
  burn9: burnDark.burn9,
  burn10: burnDark.burn10,
  burn11: burnDark.burn11,
  burn12: burnDark.burn12,

  moon1: moonDark.moon1,
  moon2: moonDark.moon2,
  moon3: moonDark.moon3,
  moon4: moonDark.moon4,
  moon5: moonDark.moon5,
  moon6: moonDark.moon6,
  moon7: moonDark.moon7,
  moon8: moonDark.moon8,
  moon9: moonDark.moon9,
  moon10: moonDark.moon10,
  moon11: moonDark.moon11,
  moon12: moonDark.moon12,
}

export const kitDarkColors = baseKitDarkThemeColors
