import * as React from 'react'
import Head from 'next/head'

import {
  AccordionDemo,
  ButtonDemo,
  ContainerDemo,
  CopyTextFieldDemo,
  CheckboxDemo,
  GridDemo,
  RadioGroupDemo,
  SwitchDemo,
  SelectDemo,
  TabsDemo,
  DialogDemo,
  PopoverDemo,
  BadgeDemo,
} from '@/demo'
import {SectionGap} from '@/components/SectionGap'
import {Header} from '@/components/Header'

function Components() {
  return (
    <>
      <Head>
        <title>Atelier® Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* <!-- Components go here --> */}

      <SectionGap />
      <ContainerDemo />
      <SectionGap />
      <GridDemo />
      <SectionGap />
      <BadgeDemo />
      <SectionGap />
      <CheckboxDemo />
      <SectionGap />
      <CopyTextFieldDemo />
      <SectionGap />
      <ButtonDemo />
      <SectionGap />
      <SwitchDemo />
      <SectionGap />
      <PopoverDemo />
      <SectionGap />
      <DialogDemo />
      <SectionGap />
      <SelectDemo />
      <SectionGap />
      <RadioGroupDemo />
      <SectionGap />

      <SectionGap />
      <TabsDemo />
      <SectionGap />
      <AccordionDemo />
    </>
  )
}

export default Components
