import * as React from 'react'
import Head from 'next/head'

import {Section} from 'atlr.kit'
import {AppWrapper} from '@/components/AppWrapper'
import {
  AccordionDemo,
  ButtonDemo,
  CheckboxDemo,
  ContainerDemo,
  CopyTextFieldDemo,
  GridDemo,
  RadioGroupDemo,
  RevealDemo,
  SwitchDemo,
  TabsDemo,
} from '@/demo'
import {SectionGap} from '@/components/SectionGap'
import {AtelierKitLogo} from '@/components/AtelierKit.Logo'

function Components() {
  return (
    <>
      <Head>
        <title>Atelier® Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <!-- Components go here --> */}

      <AppWrapper>
        <AtelierKitLogo />
        <SectionGap />
        <ContainerDemo />
        <SectionGap />
        <CopyTextFieldDemo />
        <SectionGap />
        <ButtonDemo />
        <SectionGap />
        <SwitchDemo />
        <SectionGap />
        <RadioGroupDemo />
        <SectionGap />
        <CheckboxDemo />
        <SectionGap />
        <TabsDemo />
        <SectionGap />
        <AccordionDemo />
        <SectionGap />
        <RevealDemo />
        <SectionGap />
        <GridDemo />
        <SectionGap />
      </AppWrapper>
    </>
  )
}

export default Components
