import * as React from 'react'
import Head from 'next/head'

import {Canvas, KitColors} from '@atlr/kit'
import {AtelierKitLogo} from '@/components/AtelierKit.Logo'
import {AppWrapper} from '@/components/AppWrapper'

const color = KitColors.slate11

function Index() {
  return (
    <>
      <Head>
        <title>Atelier® Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppWrapper>
        <Canvas>
          <AtelierKitLogo color={color} />
        </Canvas>
      </AppWrapper>
    </>
  )
}

export default Index
