import * as React from 'react'
import Head from 'next/head'
import Image from 'next/image'

import {Button, Canvas, Flex, KitColors} from 'atlr.kit'
import {AtelierKitLogo} from '@/components/AtelierKit.Logo'
import {AppWrapper} from '@/components/AppWrapper'
import {BlurredCanvas} from '@/components/BlurredCanvas'
import mainBackdrop from '../../public/main.png'

const color = KitColors.slate12

function Index() {
  return (
    <>
      <Head>
        <title>Atelier® Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppWrapper>
        <Canvas>
          <Flex direction="column" align="center" justify="center">
            <AtelierKitLogo color={color} />
            <Button size="sm" href="/components" secondary>
              View Components
            </Button>
          </Flex>
        </Canvas>
      </AppWrapper>

      <BlurredCanvas />
      <Image src={mainBackdrop} alt="src" fill style={{width: '100%', height: '100%'}} />
    </>
  )
}

export default Index
